[job]
dump_folder = "./outputs"
description = "Llama 4 debug training with FSDP+EP on 4 GPUs"
print_args = false
use_for_integration_test = true

[model]
name = "llama4"
flavor = "debugmodel"
tokenizer_path = "./tests/assets/tokenizer"

[optimizer]
name = "AdamW"
lr = 8e-4
eps = 1e-8

[metrics]
log_freq = 1

[training]
local_batch_size = 1
seq_len = 12
max_norm = 1.0
steps = 10
compile = false
dataset = "c4_test"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1
expert_parallel_degree = 1

[checkpoint]
enable_checkpoint = false 