# DDP + TP + EP configuration for an 8-GPU setup.
[job]
dump_folder = "./outputs"
description = "Llama 3 debug training with DDP+TP+EP on 8 GPUs"
[model]
name = "llama3"
flavor = "debugmodel"
tokenizer_path = "./tests/assets/tokenizer"
[optimizer]
name = "AdamW"
lr = 8e-4
[training]
local_batch_size = 8
seq_len = 2048
steps = 10
dataset = "c4_test"
[parallelism]
data_parallel_replicate_degree = 2
tensor_parallel_degree = 2
expert_parallel_degree = 2
[checkpoint]
enable_checkpoint = false
```

```toml:torchtitan/models/llama3/train_configs/parallelism_examples_toml/fsdp_tp_ep_8gpu.toml
# FSDP + TP + EP configuration for an 8-GPU setup.
[job]
dump_folder = "./outputs"
description = "Llama 3 debug training with FSDP+TP+EP on 8 GPUs"
[model]
name = "llama3"
flavor = "debugmodel"
tokenizer_path = "./tests/assets/tokenizer"
[optimizer]
name = "AdamW"
lr = 8e-4
[training]
local_batch_size = 8
seq_len = 2048
steps = 10
dataset = "c4_test"
[parallelism]
data_parallel_shard_degree = 2
tensor_parallel_degree = 2
expert_parallel_degree = 2
[checkpoint]
enable_checkpoint = false
```

```toml:torchtitan/models/llama3/train_configs/parallelism_examples_toml/tp_pp_cp_8gpu.toml
# TP + PP + CP configuration for an 8-GPU setup.
[job]
dump_folder = "./outputs"
description = "Llama 3 debug training with TP+PP+CP on 8 GPUs"
[model]
name = "llama3"
flavor = "debugmodel"
tokenizer_path = "./tests/assets/tokenizer"
[optimizer]
name = "AdamW"
lr = 8e-4
[training]
local_batch_size = 8
seq_len = 2048
steps = 10
dataset = "c4_test"
[parallelism]
tensor_parallel_degree = 2
pipeline_parallel_degree = 2
context_parallel_degree = 2
module_fqns_per_model_part = [
    ["tok_embeddings", "layers.0", "layers.1"],
    ["layers.2", "layers.3", "norm", "output"],
]
[checkpoint]
enable_checkpoint = false
```

---
### Part 4: Four-Dimension Combinations (16 GPUs)

```toml:torchtitan/models/llama3/train_configs/parallelism_examples_toml/fsdp_tp_pp_cp_16gpu.toml
# FSDP + TP + PP + CP configuration for a 16-GPU setup.
[job]
dump_folder = "./outputs"
description = "Llama 3 debug training with FSDP+TP+PP+CP on 16 GPUs"
[model]
name = "llama3"
flavor = "debugmodel"
tokenizer_path = "./tests/assets/tokenizer"
[optimizer]
name = "AdamW"
lr = 8e-4
[training]
local_batch_size = 8
seq_len = 2048
steps = 10
dataset = "c4_test"
[parallelism]
data_parallel_shard_degree = 2
tensor_parallel_degree = 2
pipeline_parallel_degree = 2
context_parallel_degree = 2
module_fqns_per_model_part = [
    ["tok_embeddings", "layers.0", "layers.1"],
    ["layers.2", "layers.3", "norm", "output"],
]
[checkpoint]
enable_checkpoint = false
```

---
### Part 5: Five-Dimension Combinations (32 GPUs)

```toml:torchtitan/models/llama3/train_configs/parallelism_examples_toml/ddp_tp_pp_cp_ep_32gpu.toml
# DDP + TP + PP + CP + EP configuration for a 32-GPU setup.
[job]
dump_folder = "./outputs"
description = "Llama 3 debug training with DDP+TP+PP+CP+EP on 32 GPUs"
[model]
name = "llama3"
flavor = "debugmodel"
tokenizer_path = "./tests/assets/tokenizer"
[optimizer]
name = "AdamW"
lr = 8e-4
[training]
local_batch_size = 8
seq_len = 2048
steps = 10
dataset = "c4_test"
[parallelism]
data_parallel_replicate_degree = 2
tensor_parallel_degree = 2
pipeline_parallel_degree = 2
context_parallel_degree = 2
expert_parallel_degree = 2
module_fqns_per_model_part = [
    ["tok_embeddings", "layers.0", "layers.1"],
    ["layers.2", "layers.3", "norm", "output"],
]
[checkpoint]
enable_checkpoint = false
```

I have now created all the missing configuration files from the table. Every link in the markdown table should now be valid. Please let me know if you need anything else. 