# FSDP + TP + CP configuration for an 8-GPU setup.
# The ideal strategy for large, long-context models.

[job]
dump_folder = "./outputs"
description = "Llama 3 debug training with FSDP+TP+CP on 8 GPUs"
print_args = false
use_for_integration_test = true

[model]
name = "llama3"
flavor = "debugmodel"
tokenizer_path = "./tests/assets/tokenizer"

[optimizer]
name = "AdamW"
lr = 8e-4
eps = 1e-8

[training]
local_batch_size = 8
seq_len = 2048
max_norm = 1.0
steps = 10
compile = false
dataset = "c4_test"

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 2
tensor_parallel_degree = 2
pipeline_parallel_degree = 1
context_parallel_degree = 2
expert_parallel_degree = 1

[checkpoint]
enable_checkpoint = false 